language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
  - src/node_modules

before_install:
  - cd src

install:
  - yarn install

script:
  - yarn run lint
  - yarn run type-check
  - yarn run test
  - yarn run build

deploy:
  provider: netlify
  site: "1b8fd276-1d98-4e97-a3e2-0d9c6aeda309"
  dir: "../dist/"
  prod: true
  edge: true
  on:
    branch: master