language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
  - src/node_modules

before_install:
  - cd src

install:
  - yarn install

script:
  - yarn run lint
  - yarn run type-check
  - yarn run test
  - yarn run build